In [3]:
import pandas as pd
import numpy as np
# import gensim
import pandas as pd
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [4]:
messages = pd.read_csv('/content/SMSSpamCollection.txt', sep='\t', names=['label', 'message'])
messages[:2]

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...

In [5]:
corpus = []
for i in range(len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower().split()
    review = [ps.stem(word) for word in review if word not in stopwords.words()]
    review = ' '.join(review)
    corpus.append(review)
corpus[:2]

['jurong point crazi avail bugi great world buffet amor', 'lar joke wif']

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X = tv.fit_transform(corpus).toarray()

In [17]:
X.shape

(5572, 2500)

In [79]:
tv.vocabulary_

{'point': np.int64(1581),
 'crazi': np.int64(472),
 'avail': np.int64(116),
 'bugi': np.int64(239),
 'great': np.int64(851),
 'world': np.int64(2433),
 'lar': np.int64(1114),
 'joke': np.int64(1069),
 'wif': np.int64(2389),
 'free': np.int64(746),
 'entri': np.int64(643),
 'wkli': np.int64(2415),
 'comp': np.int64(413),
 'win': np.int64(2392),
 'cup': np.int64(489),
 'final': np.int64(708),
 'tkt': np.int64(2143),
 'st': np.int64(1974),
 'text': np.int64(2098),
 'receiv': np.int64(1697),
 'question': np.int64(1656),
 'std': np.int64(1989),
 'txt': np.int64(2198),
 'rate': np.int64(1673),
 'appli': np.int64(78),
 'free entri': np.int64(753),
 'entri wkli': np.int64(646),
 'wkli comp': np.int64(2416),
 'cup final': np.int64(490),
 'std txt': np.int64(1990),
 'txt rate': np.int64(2206),
 'rate appli': np.int64(1675),
 'dun': np.int64(604),
 'earli': np.int64(612),
 'usf': np.int64(2287),
 'live': np.int64(1171),
 'freemsg': np.int64(766),
 'hey': np.int64(927),
 'darl': np.int64(514),
 'week': np.int64(2362),
 'word': np.int64(2425),
 'back': np.int64(133),
 'fun': np.int64(787),
 'tb': np.int64(2072),
 'xxx': np.int64(2473),
 'send': np.int64(1822),
 'rcv': np.int64(1679),
 'brother': np.int64(229),
 'speak': np.int64(1951),
 'treat': np.int64(2181),
 'request': np.int64(1739),
 'mell': np.int64(1283),
 'oru': np.int64(1493),
 'set': np.int64(1845),
 'callertun': np.int64(291),
 'caller': np.int64(288),
 'press': np.int64(1613),
 'copi': np.int64(453),
 'friend': np.int64(772),
 'set callertun': np.int64(1846),
 'callertun caller': np.int64(292),
 'caller press': np.int64(289),
 'press copi': np.int64(1614),
 'copi friend': np.int64(454),
 'friend callertun': np.int64(773),
 'winner': np.int64(2402),
 'valu': np.int64(2295),
 'network': np.int64(1414),
 'custom': np.int64(496),
 'select': np.int64(1818),
 'prize': np.int64(1625),
 'reward': np.int64(1753),
 'claim': np.int64(363),
 'call': np.int64(255),
 'code': np.int64(389),
 'valid': np.int64(2292),
 'hour': np.int64(973),
 'claim call': np.int64(364),
 'call claim': np.int64(260),
 'claim code': np.int64(365),
 'valid hour': np.int64(2293),
 'mobil': np.int64(1332),
 'month': np.int64(1355),
 'entitl': np.int64(641),
 'updat': np.int64(2238),
 'latest': np.int64(1118),
 'colour': np.int64(403),
 'camera': np.int64(295),
 'co': np.int64(385),
 'entitl updat': np.int64(642),
 'updat latest': np.int64(2240),
 'latest colour': np.int64(1120),
 'free call': np.int64(749),
 'call mobil': np.int64(275),
 'mobil updat': np.int64(1343),
 'updat co': np.int64(2239),
 'co free': np.int64(386),
 'gonna': np.int64(834),
 'home': np.int64(954),
 'talk': np.int64(2066),
 'stuff': np.int64(2019),
 'anymor': np.int64(72),
 'tonight': np.int64(2166),
 'cri': np.int64(478),
 'today': np.int64(2150),
 'chanc': np.int64(331),
 'cash': np.int64(312),
 'pound': np.int64(1597),
 'cost': np.int64(456),
 'day': np.int64(519),
 'repli': np.int64(1726),
 'hl': np.int64(938),
 'info': np.int64(1020),
 'chanc win': np.int64(333),
 'win cash': np.int64(2393),
 'repli hl': np.int64(1730),
 'hl info': np.int64(939),
 'urgent': np.int64(2275),
 'membership': np.int64(1286),
 'www': np.int64(2455),
 'net': np.int64(1411),
 'pobox': np.int64(1577),
 'ldnw': np.int64(1134),
 'week free': np.int64(2365),
 'txt word': np.int64(2209),
 'search': np.int64(1810),
 'promis': np.int64(1638),
 'wonder': np.int64(2422),
 'bless': np.int64(185),
 'time': np.int64(2130),
 'date': np.int64(517),
 'sunday': np.int64(2037),
 'credit': np.int64(476),
 'click': np.int64(377),
 'wap': np.int64(2341),
 'link': np.int64(1167),
 'messag': np.int64(1290),
 'http': np.int64(982),
 'watch': np.int64(2345),
 'rememb': np.int64(1717),
 'spell': np.int64(1961),
 'naughti': np.int64(1409),
 'make': np.int64(1241),
 'wet': np.int64(2382),
 'fine': np.int64(714),
 'feel': np.int64(693),
 'england': np.int64(632),
 'miss': np.int64(1315),
 'goal': np.int64(829),
 'team': np.int64(2079),
 'news': np.int64(1418),
 'ur': np.int64(2245),
 'nation': np.int64(1405),
 'scotland': np.int64(1807),
 'wq': np.int64(2444),
 'pay': np.int64(1516),
 'stock': np.int64(1992),
 'comin': np.int64(411),
 'aft': np.int64(35),
 'finish': np.int64(717),
 'lunch': np.int64(1225),
 'str': np.int64(2012),
 'ard': np.int64(84),
 'smth': np.int64(1922),
 'ard smth': np.int64(85),
 'alright': np.int64(56),
 'meet': np.int64(1277),
 'sooner': np.int64(1938),
 'forc': np.int64(734),
 'eat': np.int64(618),
 'hungri': np.int64(985),
 'suck': np.int64(2029),
 'mark': np.int64(1252),
 'worri': np.int64(2435),
 'sick': np.int64(1875),
 'turn': np.int64(2196),
 'pizza': np.int64(1549),
 'convinc': np.int64(449),
 'catch': np.int64(320),
 'bu': np.int64(234),
 'fri': np.int64(770),
 'egg': np.int64(623),
 'tea': np.int64(2076),
 'mom': np.int64(1350),
 'left': np.int64(1142),
 'dinner': np.int64(567),
 'love': np.int64(1200),
 'amp': np.int64(60),
 'pack': np.int64(1496),
 'car': np.int64(304),
 'room': np.int64(1767),
 'work': np.int64(2428),
 'wait': np.int64(2328),
 'clear': np.int64(376),
 'child': np.int64(352),
 'cheer': np.int64(348),
 'quick': np.int64(1657),
 'subscript': np.int64(2027),
 'rington': np.int64(1756),
 'uk': np.int64(2221),
 'charg': np.int64(337),
 'confirm': np.int64(426),
 'mobil charg': np.int64(1334),
 'msg': np.int64(1378),
 'learn': np.int64(1136),
 'lesson': np.int64(1148),
 'oop': np.int64(1472),
 'roommat': np.int64(1768),
 'letter': np.int64(1150),
 'decid': np.int64(538),
 'saturday': np.int64(1795),
 'tomo': np.int64(2161),
 'invit': np.int64(1033),
 'pl': np.int64(1550),
 'ahead': np.int64(43),
 'want': np.int64(2340),
 'weekend': np.int64(2370),
 'abiola': np.int64(4),
 'great weekend': np.int64(855),
 'forget': np.int64(736),
 'crave': np.int64(471),
 'sweet': np.int64(2055),
 'yummi': np.int64(2495),
 'burn': np.int64(242),
 'sm': np.int64(1910),
 'nokia': np.int64(1429),
 'camcord': np.int64(293),
 'deliveri': np.int64(549),
 'tomorrow': np.int64(2162),
 'msg call': np.int64(1379),
 'call repli': np.int64(280),
 'free nokia': np.int64(758),
 'nokia mobil': np.int64(1433),
 'mobil free': np.int64(1338),
 'free camcord': np.int64(750),
 'call deliveri': np.int64(262),
 'deliveri tomorrow': np.int64(551),
 'hope': np.int64(960),
 'lt': np.int64(1217),
 'gt': np.int64(862),
 'inch': np.int64(1011),
 'lt gt': np.int64(1219),
 'gt inch': np.int64(865),
 'call messag': np.int64(273),
 'miss call': np.int64(1317),
 'nigeria': np.int64(1421),
 'tyler': np.int64(2216),
 'bit': np.int64(179),
 'hospit': np.int64(969),
 'tell': np.int64(2087),
 'weak': np.int64(2355),
 'think': np.int64(2114),
 'class': np.int64(373),
 'gram': np.int64(847),
 'run': np.int64(1781),
 'half': np.int64(894),
 'fyi': np.int64(790),
 'ride': np.int64(1754),
 'morn': np.int64(1359),
 'crash': np.int64(470),
 'place': np.int64(1559),
 'wow': np.int64(2441),
 'realiz': np.int64(1693),
 'embarass': np.int64(625),
 'happi': np.int64(904),
 'sorri': np.int64(1940),
 'give': np.int64(822),
 'offer': np.int64(1460),
 'ac': np.int64(6),
 'red': np.int64(1703),
 'play': np.int64(1562),
 'ice': np.int64(995),
 'correct': np.int64(455),
 'sm ac': np.int64(1911),
 'yesterday': np.int64(2487),
 'find': np.int64(710),
 'url': np.int64(2282),
 'congrat': np.int64(428),
 'year': np.int64(2482),
 'special': np.int64(1953),
 'cinema': np.int64(361),
 'pass': np.int64(1511),
 'bx': np.int64(246),
 'ip': np.int64(1037),
 'pm': np.int64(1573),
 'bx ip': np.int64(247),
 'ip pm': np.int64(1038),
 'sorri call': np.int64(1941),
 'call meet': np.int64(272),
 'reach': np.int64(1683),
 'seri': np.int64(1837),
 'pick': np.int64(1539),
 'move': np.int64(1369),
 'pain': np.int64(1500),
 'kill': np.int64(1093),
 'girl': np.int64(819),
 'situat': np.int64(1895),
 'part': np.int64(1507),
 'check': np.int64(347),
 'iq': np.int64(1041),
 'forev': np.int64(735),
 'doubl': np.int64(587),
 'hair': np.int64(893),
 'wun': np.int64(2454),
 'cut': np.int64(501),
 'short': np.int64(1864),
 'nice': np.int64(1419),
 'cut short': np.int64(502),
 'pleas': np.int64(1568),
 'advis': np.int64(29),
 'recent': np.int64(1701),
 'review': np.int64(1752),
 'mob': np.int64(1329),
 'award': np.int64(122),
 'bonu': np.int64(198),
 'award bonu': np.int64(123),
 'prize call': np.int64(1627),
 'song': np.int64(1932),
 'dedic': np.int64(542),
 'frnd': np.int64(780),
 'rpli': np.int64(1774),
 'song dedic': np.int64(1933),
 'send ur': np.int64(1835),
 'complimentari': np.int64(418),
 'trip': np.int64(2183),
 'di': np.int64(558),
 'ls': np.int64(1216),
 'ur award': np.int64(2246),
 'hear': np.int64(916),
 'plane': np.int64(1561),
 'lucki': np.int64(1222),
 'save': np.int64(1799),
 'money': np.int64(1353),
 'hee': np.int64(923),
 'babe': np.int64(130),
 'wanna': np.int64(2339),
 'xx': np.int64(2472),
 'machan': np.int64(1230),
 'call free': np.int64(263),
 'cool': np.int64(451),
 'respect': np.int64(1743),
 'oper': np.int64(1474),
 'job': np.int64(1063),
 'stop': np.int64(1996),
 'urgnt': np.int64(2281),
 'real': np.int64(1690),
 'ticket': np.int64(2127),
 'start': np.int64(1983),
 'bed': np.int64(158),
 'coin': np.int64(394),
 'gotta': np.int64(842),
 'kano': np.int64(1080),
 'download': np.int64(590),
 'wen': np.int64(2379),
 'wen ur': np.int64(2380),
 'stand': np.int64(1979),
 'close': np.int64(379),
 'night': np.int64(1422),
 'spent': np.int64(1963),
 'late': np.int64(1117),
 'afternoon': np.int64(37),
 'mean': np.int64(1272),
 'moro': np.int64(1364),
 'includ': np.int64(1012),
 'sheet': np.int64(1856),
 'smile': np.int64(1916),
 'pleasur': np.int64(1569),
 'troubl': np.int64(2184),
 'rain': np.int64(1666),
 'sum': np.int64(2034),
 'hurt': np.int64(988),
 'becoz': np.int64(157),
 'love smile': np.int64(1210),
 'servic': np.int64(1839),
 'repres': np.int64(1736),
 'guarante': np.int64(876),
 'call custom': np.int64(261),
 'custom servic': np.int64(500),
 'servic repres': np.int64(1844),
 'repres pm': np.int64(1738),
 'pm guarante': np.int64(1575),
 'guarante cash': np.int64(879),
 'cash prize': np.int64(317),
 'plan': np.int64(1560),
 'buy': np.int64(244),
 'show': np.int64(1867),
 'collect': np.int64(399),
 'simpli': np.int64(1885),
 'password': np.int64(1514),
 'verifi': np.int64(2297),
 'fml': np.int64(729),
 'box': np.int64(212),
 'mk': np.int64(1323),
 'free rington': np.int64(761),
 'box mk': np.int64(215),
 'movi': np.int64(1370),
 'abt': np.int64(5),
 'load': np.int64(1175),
 'loan': np.int64(1176),
 'wk': np.int64(2411),
 'hol': np.int64(943),
 'forgot': np.int64(737),
 'appoint': np.int64(79),
 'shower': np.int64(1872),
 'prob': np.int64(1631),
 'coffe': np.int64(393),
 'price': np.int64(1616),
 'long': np.int64(1186),
 'legal': np.int64(1144),
 'ave': np.int64(117),
 'drive': np.int64(599),
 'test': np.int64(2097),
 'guess': np.int64(884),
 'gave': np.int64(799),
 'boston': np.int64(207),
 'chang': np.int64(334),
 'locat': np.int64(1179),
 'nyc': np.int64(1459),
 'cuz': np.int64(504),
 'page': np.int64(1498),
 'umma': np.int64(2225),
 'life': np.int64(1155),
 'lot': np.int64(1195),
 'dear': np.int64(532),
 'love lot': np.int64(1208),
 'wish': np.int64(2404),
 'birthday': np.int64(175),
 'aight': np.int64(45),
 'hit': np.int64(936),
 'address': np.int64(22),
 'consid': np.int64(433),
 'comput': np.int64(419),
 'lie': np.int64(1154),
 'busi': np.int64(243),
 'research': np.int64(1741),
 'thing': np.int64(2113),
 'scare': np.int64(1800),
 'mah': np.int64(1235),
 'contact': np.int64(434),
 'draw': np.int64(591),
 'hr': np.int64(980),
 'ppm': np.int64(1603),
 'contact weekend': np.int64(444),
 'weekend draw': np.int64(2372),
 'draw show': np.int64(593),
 'show prize': np.int64(1869),
 'prize guarante': np.int64(1629),
 'guarante call': np.int64(878),
 'code valid': np.int64(392),
 'valid hr': np.int64(2294),
 'hr ppm': np.int64(981),
 'wa': np.int64(2327),
 'juz': np.int64(1078),
 'tt': np.int64(2192),
 'eatin': np.int64(619),
 'weight': np.int64(2376),
 'haha': np.int64(891),
 'happen': np.int64(902),
 'enter': np.int64(636),
 'cabin': np.int64(249),
 'boss': np.int64(205),
 'felt': np.int64(697),
 'askd': np.int64(100),
 'apart': np.int64(75),
 'enter cabin': np.int64(637),
 'cabin happi': np.int64(250),
 'happi day': np.int64(906),
 'day boss': np.int64(521),
 'boss felt': np.int64(206),
 'felt special': np.int64(698),
 'special askd': np.int64(1955),
 'askd lunch': np.int64(101),
 'lunch lunch': np.int64(1227),
 'lunch invit': np.int64(1226),
 'invit apart': np.int64(1034),
 'holiday': np.int64(948),
 'flight': np.int64(725),
 'winner special': np.int64(2403),
 'special select': np.int64(1957),
 'select receiv': np.int64(1819),
 'holiday flight': np.int64(951),
 'flight speak': np.int64(726),
 'speak live': np.int64(1952),
 'live oper': np.int64(1173),
 'oper claim': np.int64(1475),
 'friday': np.int64(771),
 'need': np.int64(1410),
 'uncl': np.int64(2227),
 'inform': np.int64(1021),
 'school': np.int64(1804),
 'directli': np.int64(571),
 'food': np.int64(731),
 'privat': np.int64(1623),
 'account': np.int64(13),
 'statement': np.int64(1985),
 'unredeem': np.int64(2232),
 'identifi': np.int64(998),
 'expir': np.int64(666),
 'privat account': np.int64(1624),
 'account statement': np.int64(14),
 'statement show': np.int64(1986),
 'show unredeem': np.int64(1871),
 'point claim': np.int64(1583),
 'call identifi': np.int64(267),
 'identifi code': np.int64(999),
 'code expir': np.int64(390),
 'landlin': np.int64(1109),
 'urgent mobil': np.int64(2280),
 'mobil award': np.int64(1333),
 'bonu caller': np.int64(199),
 'caller prize': np.int64(290),
 'contact call': np.int64(435),
 'call landlin': np.int64(270),
 'voda': np.int64(2314),
 'number': np.int64(1452),
 'end': np.int64(627),
 'match': np.int64(1257),
 'quot': np.int64(1661),
 'standard': np.int64(1980),
 'app': np.int64(76),
 'today voda': np.int64(2159),
 'voda number': np.int64(2315),
 'number end': np.int64(1454),
 'end select': np.int64(629),
 'receiv award': np.int64(1698),
 'match call': np.int64(1258),
 'call quot': np.int64(279),
 'quot claim': np.int64(1662),
 'code standard': np.int64(391),
 'standard rate': np.int64(1981),
 'rate app': np.int64(1674),
 'predict': np.int64(1609),
 'time finish': np.int64(2133),
 'yetund': np.int64(2488),
 'bother': np.int64(208),
 'bak': np.int64(138),
 'long time': np.int64(1188),
 'time give': np.int64(2134),
 'give call': np.int64(824),
 'dear call': np.int64(533),
 'answer': np.int64(71),
 'sunshin': np.int64(2041),
 'quiz': np.int64(1659),
 'top': np.int64(2168),
 'soni': np.int64(1934),
 'dvd': np.int64(610),
 'player': np.int64(1565),
 'countri': np.int64(461),
 'ansr': np.int64(69),
 'sp': np.int64(1948),
 'tyron': np.int64(2219),
 'sunshin quiz': np.int64(2042),
 'quiz wkli': np.int64(1660),
 'wkli win': np.int64(2418),
 'win top': np.int64(2397),
 'top soni': np.int64(2169),
 'soni dvd': np.int64(1935),
 'dvd player': np.int64(611),
 'player countri': np.int64(1566),
 'txt ansr': np.int64(2199),
 'ansr sp': np.int64(70),
 'sp tyron': np.int64(1949),
 'laid': np.int64(1105),
 'dog': np.int64(583),
 'direct': np.int64(569),
 'join': np.int64(1067),
 'largest': np.int64(1115),
 'bt': np.int64(232),
 'txting': np.int64(2214),
 'nt': np.int64(1447),
 'ec': np.int64(620),
 'locat direct': np.int64(1180),
 'direct ur': np.int64(570),
 'ur mob': np.int64(2261),
 'join uk': np.int64(1068),
 'uk largest': np.int64(2222),
 'largest dog': np.int64(1116),
 'dog network': np.int64(584),
 'haf': np.int64(890),
 'yiju': np.int64(2489),
 'befor': np.int64(162),
 'activ': np.int64(18),
 'chat': np.int64(342),
 'age': np.int64(40),
 'yr': np.int64(2493),
 'lazi': np.int64(1129),
 'type': np.int64(2217),
 'lect': np.int64(1140),
 'sir': np.int64(1890),
 'mail': np.int64(1238),
 'sir wait': np.int64(1891),
 'swt': np.int64(2059),
 'tire': np.int64(2141),
 'lovabl': np.int64(1197),
 'person': np.int64(1525),
 'coz': np.int64(465),
 'biggest': np.int64(172),
 'heart': np.int64(918),
 'gud': np.int64(881),
 'open': np.int64(1473),
 'what': np.int64(2383),
 'take': np.int64(2063),
 'sexi': np.int64(1849),
 'local': np.int64(1178),
 'luv': np.int64(1228),
 'netcollex': np.int64(1413),
 'repli stop': np.int64(1733),
 'begin': np.int64(164),
 'qatar': np.int64(1651),
 'pray': np.int64(1608),
 'hard': np.int64(910),
 'delet': np.int64(547),
 'wine': np.int64(2401),
 'thk': np.int64(2117),
 'window': np.int64(2400),
 'shirt': np.int64(1858),
 'dream': np.int64(595),
 'joy': np.int64(1072),
 'tv': np.int64(2197),
 'leav': np.int64(1137),
 'hous': np.int64(974),
 'leav hous': np.int64(1138),
 'interview': np.int64(1031),
 'boy': np.int64(219),
 'arrang': np.int64(91),
 'wait call': np.int64(2329),
 'receiv cash': np.int64(1699),
 'cash holiday': np.int64(316),
 'safe': np.int64(1789),
 'parent': np.int64(1502),
 'hand': np.int64(897),
 'excit': np.int64(660),
 'spend': np.int64(1962),
 'make happi': np.int64(1244),
 'invit friend': np.int64(1035),
 'friend repli': np.int64(775),
 'repli www': np.int64(1734),
 'www sm': np.int64(2460),
 'stop send': np.int64(2002),
 'send stop': np.int64(1832),
 'stop frnd': np.int64(2000),
 'order': np.int64(1488),
 'content': np.int64(445),
 'goto': np.int64(840),
 'internet': np.int64(1030),
 'menu': np.int64(1287),
 'ur mobil': np.int64(2262),
 'modul': np.int64(1349),
 'urgent contact': np.int64(2278),
 'avoid': np.int64(118),
 'wit': np.int64(2409),
 'escap': np.int64(649),
 'fanci': np.int64(678),
 'complet': np.int64(417),
 'form': np.int64(739),
 'wast': np.int64(2343),
 'bank': np.int64(141),
 'hmmm': np.int64(941),
 'hop': np.int64(959),
 'muz': np.int64(1401),
 'discuss': np.int64(575),
 'liao': np.int64(1151),
 'come': np.int64(407),
 'time come': np.int64(2131),
 'bloodi': np.int64(189),
 'hell': np.int64(925),
 'believ': np.int64(165),
 'mr': np.int64(1373),
 'bath': np.int64(145),
 'carlo': np.int64(309),
 'stay': np.int64(1988),
 'smoke': np.int64(1921),
 'worth': np.int64(2438),
 'spoke': np.int64(1967),
 'satisfi': np.int64(1794),
 'experi': np.int64(665),
 'lift': np.int64(1157),
 'especi': np.int64(650),
 'studi': np.int64(2018),
 'gr': np.int64(845),
 'trust': np.int64(2185),
 'guy': np.int64(887),
 'bye': np.int64(248),
 'mummi': np.int64(1393),
 'boytoy': np.int64(220),
 'awesom': np.int64(129),
 'minut': np.int64(1308),
 'haha awesom': np.int64(892),
 'freephon': np.int64(767),
 'repres freephon': np.int64(1737),
 'freephon pm': np.int64(768),
 'xma': np.int64(2470),
 'radio': np.int64(1665),
 'ju': np.int64(1075),
 'si': np.int64(1874),
 'reach home': np.int64(1685),
 'uniqu': np.int64(2229),
 'co uk': np.int64(388),
 'touch': np.int64(2172),
 'deal': np.int64(531),
 'great week': np.int64(854),
 'cours': np.int64(463),
 'suggest': np.int64(2031),
 'settl': np.int64(1847),
 'gr day': np.int64(846),
 'mrng': np.int64(1374),
 'hav': np.int64(913),
 'gud mrng': np.int64(883),
 'mrng dear': np.int64(1375),
 'hav nice': np.int64(914),
 'nice day': np.int64(1420),
 'stori': np.int64(2010),
 'person stori': np.int64(1527),
 'dead': np.int64(530),
 'tmr': np.int64(2145),
 'orchard': np.int64(1487),
 'mrt': np.int64(1376),
 'kate': np.int64(1081),
 'even': np.int64(655),
 'found': np.int64(743),
 'buck': np.int64(236),
 'gt buck': np.int64(863),
 'darlin': np.int64(515),
 'ive': np.int64(1047),
 'colleg': np.int64(402),
 'love kate': np.int64(1205),
 'success': np.int64(2028),
 'decim': np.int64(539),
 'balanc': np.int64(139),
 'rs': np.int64(1775),
 'transact': np.int64(2178),
 'id': np.int64(996),
 'lt decim': np.int64(1218),
 'decim gt': np.int64(540),
 'rs lt': np.int64(1776),
 'goodmorn': np.int64(835),
 'sleep': np.int64(1904),
 'oso': np.int64(1494),
 'oredi': np.int64(1490),
 'straight': np.int64(2013),
 'connect': np.int64(432),
 'bill': np.int64(173),
 'shoot': np.int64(1861),
 'big': np.int64(171),
 'readi': np.int64(1689),
 'break': np.int64(223),
 'semest': np.int64(1821),
 'hope great': np.int64(964),
 'leh': np.int64(1145),
 'sound': np.int64(1944),
 'head': np.int64(915),
 'slept': np.int64(1906),
 'past': np.int64(1515),
 'easi': np.int64(615),
 'exam': np.int64(658),

In [26]:
y = messages['label'] == 'ham'
y = y.astype('int8')
y.dtype, y.shape

(dtype('int8'), (5572,))

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [28]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [29]:
spam_detect_model.score(X_test, y_test)

0.9757847533632287

In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test, spam_detect_model.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91       160
           1       0.97      1.00      0.99       955

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.97      1115

In [31]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [43]:
from nltk.corpus import stopwords, wordnet
def get_wordnet_pos(word):
    """Map NLTK POS tag to WordNet POS tag"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

In [54]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [57]:
nltk.pos_tag(['buying'])

[('buying', 'NN')]

In [60]:
nltk.pos_tag(['buying'])[0][1][0]

'N'

In [65]:
cached_stopwords = set(stopwords.words('english'))

def process_text(message):
    review = re.sub('[^a-zA-Z]', ' ', message)
    review = review.lower().split()
    lemmatized_words = []
    for word in review:
        if word not in cached_stopwords:
          pos_tag = get_wordnet_pos(word)
          lemmatized_words.append(lemmatizer.lemmatize(word, pos=pos_tag))
    return ' '.join(lemmatized_words)

In [67]:
messages['message'] = messages['message'].apply(process_text)

In [74]:
lemmatizer.lemmatize('better',pos=nltk.pos_tag(['better'])[0][1][0].lower())

'well'

In [77]:
messages.tail()

     label                                            message
5567  spam  nd time try contact u u pound prize claim easy...
5568   ham                             b go esplanade fr home
5569   ham                               pity mood suggestion
5570   ham  guy bitching act like interested buying someth...
5571   ham                                     rofl true name

In [80]:
corpus_lemmatized = messages['message'].tolist()
len(corpus_lemmatized)

5572

In [81]:
tv = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X = tv.fit_transform(corpus_lemmatized).toarray()

In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [86]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)
spam_detect_model.score(X_test, y_test)

0.9775784753363229

In [87]:
from sklearn.metrics import classification_report
print(classification_report(y_test, spam_detect_model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      0.85      0.92       160
           1       0.98      1.00      0.99       955

    accuracy                           0.98      1115
   macro avg       0.98      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

### BOW, TFIDF, Machine Learning algos

1. Processing and cleaning
2. BOW and TFIDF (Sentence-> vectors)
3. train test split
4. train

we did error split after changing orignal data
so steps 2 and 3 must be interchanged

In [89]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus_lemmatized, y, test_size=0.2, random_state=0)

In [95]:
len(X_train), len(X_test)

(4457, 1115)

## Critical step

In [97]:
X_train = tv.fit_transform(X_train).toarray()
X_test = tv.transform(X_test).toarray()

In [99]:
X_train.shape, X_test.shape

((4457, 2500), (1115, 2500))

In [101]:
spam_detect_model = MultinomialNB().fit(X_train, y_train)
spam_detect_model.score(X_test, y_test)

0.9766816143497757

In [102]:
print(classification_report(y_test, spam_detect_model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      0.84      0.91       160
           1       0.97      1.00      0.99       955

    accuracy                           0.98      1115
   macro avg       0.98      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115